### ISSUE TITLE
Contents to fix

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/tutorial#1]
- [x] Change all `geq` to `ge`.

Missing link at the end

- [x] basic/5

Needs to be complete

- [x] basic/8
- [x] basic/11
- [x] blocksvars/9
- [x] schema/9

Query is not runnable

- [x] blocksvars/2

Returns no result 
- [x] blocksvars/3

**Comment by manishrjain** [comment]
You mean change all `geq` to `ge`, right?

**Comment by sungwoncho** [comment]
yes, fixed.

**Comment by MichaelJCompton** [comment]
Hi @sungwoncho can you confirm blocksvars/3, seems to work fine for me.

**Comment by sungwoncho** [comment]
I can confirm that the query works. I think it returned no result because I had not loaded the data. This can be closed. Thanks for updating.
