### ISSUE TITLE
Syntax error in the hidden answer

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/tutorial#100]
Configs:
```
Chrome for Mac, Version 76.0.3809.132 (Oficial Version) 64 bits
Mojave 10.14.6
```
https://tour.dgraph.io/basic/5/
![Captura de Tela 2019-09-26 às 15 38 55](https://user-images.githubusercontent.com/6570955/65715588-c4da1c00-e073-11e9-92c4-62138fbd2fd7.png)

**Comment by mrcasals** [comment]
Facing the same issue in `master`: https://tour.dgraph.io/master/basic/5/

I think the error is due to these lines, which should be separated with a blank line to force the new paragraph:

https://github.com/dgraph-io/tutorial/blob/398c051de4a2fb8d347e2f850c1fea3232f27e0c/content/basic/5.md#L47-L48
