### ISSUE TITLE
The query in Step 6 doesn't return correct results.

### ISSUE THREAD

**Issue by shekarm** [dgraph-io/tutorial#102]
```
{
  everyone(func: anyofterms(name, "Michael Amit")) {
    name
    friend {
      name@ru:ko:en
      friend { expand(_all_) { expand(_all_) } }
    }
  }
}

```

The above query does not really select Amit. Since Amit doesn't have 'name' attribute, the results are correct from dgraph's perspective. But it could be confusing for the reader, who will likely expect Amit and his friends to be selected. 

It may be useful to qualify the name with name@. so Amit (who doesn't have the plain name attribute) would be selected.

**Comment by MichelDiz** [comment]
@shekarm Michael doesn't have `@en` in the dataset. So we choose one over the other or add name in Amit without tag, or set Michael's name with `@en` tag.

If I change the query to `anyofterms(name@en, "Michael Amit")`only Amit appears. I'm not sure what was the intentions of who did this part of this tutorial.

I'm ready to do it, but I need to know what decision to take.

**Comment by shekarm** [comment]
I would suggest that we use a different person other than Amit -- someone who has the name attribute defined. This way the reader gets the results that are consistent with his/her understanding. The next tutorial clarifies the name@. concept.
