### ISSUE TITLE
Tour still tells users to use the now deprecated Alter tab in Ratel

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/tutorial#111]
Haven't checked the latest tour to confirm that, but a user reported that tour is still mentioning the Alter tab in Ratel.
See discussion here: https://github.com/dgraph-io/ratel/issues/143

**Comment by MichelDiz** [comment]
There are none references to Ratel's old Alter tab. Neither in 1.0.16, 1.1.0 or Master. I have checked the whole repo.

The only reference is in `https://tour.dgraph.io/*/schema/1/`, but it can't lead users to the old tab.
And also there is only this reference for Ratel https://tour.dgraph.io/intro/2/

Or comments like
>You're able to do that through our clients, cURL or Ratel UI.

Or notices like
>{{% notice "note" %}}
Note that Schema changes are made via Alter operations only. All clients have an operation for Mutate, Query and Alter.
{{% /notice %}}

Maybe He is reading old documentation while using the Tour. I see a lot of users for some reason (maybe Google's search engine) using older documentation. This can lead to confusion.
