### ISSUE TITLE
https://play.dgraph.io/?latest not working

### ISSUE THREAD

**Issue by YueCongPKU** [dgraph-io/tutorial#113]
I run a very simple inserting sample, showed in [tutorial](https://docs.dgraph.io/tutorial-1/), but it showed "Error: t: no mutations allowed". Why is it?

![image](https://user-images.githubusercontent.com/5901729/71509286-c6f78500-28c5-11ea-8624-1ebd6ecf1f4a.png)

**Comment by YueCongPKU** [comment]
![image](https://user-images.githubusercontent.com/5901729/71509391-150c8880-28c6-11ea-80e3-1f211f03bc9c.png)

**Comment by YueCongPKU** [comment]
![image](https://user-images.githubusercontent.com/5901729/71509476-6b79c700-28c6-11ea-8373-afc1a824b754.png)

**Comment by martinmr** [comment]
That's by design. You are using play.dgraph.com which does not allow mutations.
If you want to follow the tutorial you'll have to create your own cluster.
