### ISSUE TITLE
Add actor.film in description in Schema of moredata/2 to make the predicate explicit 

### ISSUE THREAD

**Issue by iuryfukuda** [dgraph-io/tutorial#122]
### Case
taking the tour I came across with a situation in exercise `blocksvars/6/`
i needed to complete exercise, but i forgot the existence of predicate `actor.film`
i used `moredata/2`  as reference and it don't show the predicate, so i can't complete exercise and need see the spoiler to remember existence of predicate `actor.film` 

### Changes
We currently have:
```
type Person {
    name: string
    director.film: [Movie]
}
```
Add the follow line:
```
    actor.film: [Performance]
```
Change for:
```
type Person {
    name: string
    director.film: [Movie]
    actor.film: [Performance]
}
```
this could be a improvement

**Comment by MichelDiz** [comment]
This won't be necessary, as the structure of the Schema for Types has been simplified. And now you don't need to describe edges or anything.

Cheers.

**Comment by iuryfukuda** [comment]
https://github.com/dgraph-io/tutorial/pull/124
