### ISSUE TITLE
[BLOCKING]ValueError: 20.03.0 is not valid SemVer string

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/tutorial#143]
This error with semver is blocking new build releases of the tour. Dgraph have changed the versioning system. And it is not supported in semver.

ping @paulftw @danielmai

**Comment by paulftw** [comment]
@MichelDiz where did you see this error message?

**Comment by MichelDiz** [comment]
Running scripts/build.py

**Comment by MichelDiz** [comment]
How much time the changes in the repo affects the https://dgraph.io/tour/ ? it's been a few hours and nothing has changed.

**Comment by paulftw** [comment]
I think something’s off with the server.
https://github.com/dgraph-io/website/issues/111

**Comment by MichelDiz** [comment]
I see that you have fixed the semver thing. Should we close this?

**Comment by paulftw** [comment]
Yes, leftover work will go into the website repo.
Thanks for catching this and reminding to close it :)

fixed by 18887 and 382c399
