### ISSUE TITLE
Movie schema explanation

### ISSUE THREAD

**Issue by aryzing** [dgraph-io/tutorial#19]
I'm trying to follow the [`blocksvars`](https://tour.dgraph.io/blocksvars/1/) tutorial, and I'm having a hard time understanding which edges exist between which types of nodes. An image would be great ;) Alternatively, a simple explanation would suffice.

Any volunteers?

**Comment by janardhan1993** [comment]
You can use ratel(our ui) to visualize the graph and play around with it.

**Comment by aryzing** [comment]
ok thanks!
