### ISSUE TITLE
Auto gen to tour.dgraph.io not working

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/tutorial#2]
Looks like the auto generation isn't happening at the moment.

**Comment by sungwoncho** [comment]
Thanks for reporting. Hugo encountered an error and the build script exited.

Thu May 18 02:17:21 UTC 2017  Updating tutorial.
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for blocksvars/14.md: (2, 11): unexpected token for 14.md

I have fixed it for now. I will share the credential with the team for the server to help debug issues such as this.
