### ISSUE TITLE
dgraph ratel visualizer colors inacurate

### ISSUE THREAD

**Issue by aryzing** [dgraph-io/tutorial#20]
While going through the tutorial, I realized that the ratel visualizer colors are off, see image

![image](https://user-images.githubusercontent.com/4924405/34387959-6d224cd2-eb31-11e7-9169-9d23cc1e6405.png)

Happens both in docker version and well as in https://play.dgraph.io

Not sure if this is the best place for this issue, if not, let me know.

**Comment by janardhan1993** [comment]
You can create the issue on our main project(dgraph).
@gpahal Manages the UI, he will have better idea about this.

**Comment by aryzing** [comment]
ok thanks!
