### ISSUE TITLE
schema: "...predicates..." syntax in text is confusing

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/tutorial#30]
On page 9 of the schema section the first sentence, "`expand(...predicates...)` is used to query for all given predicates, ..." is confusing because of the use of `...predicates...`. What is the intention here?

Does it mean:

1. `expand(pred1, pred2, ...)`
2. `expand(<some_predicate>)` (angle bracket use here as per man page usage).
3. something else?

**Comment by MichelDiz** [comment]
Hmmm, analyzing your suggestions. I think that would confuse the reader a bit. For in examples 1 and 2, it seems to indicate (visually) the possibility of inserting predicates. What is not the intention of the function expand(All).

Anyway the intention is to indicate that this function is like a ""wildcard"". If there is something similar that exemplifies this, then we have the solution.

Although the construction of the sentence is not ideal, the simple execution of the query as it is, so already self explains its purpose.

I will close that issue, but feel free to re-open with some possible solution to that.
