### ISSUE TITLE
Why start so soon with Language Support?

### ISSUE THREAD

**Issue by wordyallen** [dgraph-io/tutorial#35]
Its an awesome feature, but maybe the fundamentals should be addressed first?

**Comment by paulftw** [comment]
`Language Support` is one of quite a few things the tutorial asks to "ignore for now, we will explain later". It could be moved to a later part, but then we'd have to ask users to add language predicates somewhere in the middle of the tutorial, which would make the tutorial longer and arguably harder to follow.

Closing this issue for now, let me know of any objections or other arguments we should consider.
