### ISSUE TITLE
Minor syntax issue  Error: unknown flag: --memory_mb

### ISSUE THREAD

**Issue by peterlamar** [dgraph-io/tutorial#38]
macos 10.12.6
Docker Version 18.03.1-ce-mac65 (24312)

From:
https://tour.dgraph.io/intro/2/
docker exec -it dgraph dgraph server --memory_mb 2048 --zero localhost:5080
Error: unknown flag: --memory_mb

This seems to work:
docker exec -it dgraph dgraph server --lru_mb 2048 --zero localhost:5080

**Comment by paulftw** [comment]
This has been fixed by PR #37 but hasn't been pushed to the live website yet.
