### ISSUE TITLE
Tutorial site not working as advertised

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/tutorial#4]
I have followed the instructions on [intro page 2](https://tour.dgraph.io/intro/2/) wrt installing the docker image, however the [page 3](https://tour.dgraph.io/intro/3/) gives me "Error: Is Dgraph running locally?". It is as demonstrated by being able to successfully run the command in a browser pointed at `localhost:8080`.

It looks like the tutorial site is trying to connect to a dgraph server not at this particular localhost.

Are there more complete instructions to get hugo to serve the tutorial locally?

**Comment by MichaelJCompton** [comment]
Hi @kortschak, thanks for pointing this out.  If you are running dgraph in Docker from the same machine that you are running the browser on, then it should be pointing to localhost.  When you point the browser to localhost:8080 you get the dgraph UI?

You can run the site locally by grabbing the source from github and running `hugo -w server` from the top level directory.

I'll test further and get back to you.

**Comment by kortschak** [comment]
>When you point the browser to localhost:8080 you get the dgraph UI?

Yes.

>You can run the site locally by grabbing the source from github and running `hugo -w server` from the top level directory.

Thanks. I figured it was going to be something like that.

**Comment by MichaelJCompton** [comment]
Does it work now that you are running the whole thing locally?

**Comment by kortschak** [comment]
Yes, it works when it's all on this machine.

**Comment by MichaelJCompton** [comment]
Hi @kortschak does this docker incantation work better for running the server from tour.dgraph.io?

docker run -it -p 127.0.0.1:8080:8080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraph --bindall=true

**Comment by kortschak** [comment]
No, still no good.

**Comment by MichaelJCompton** [comment]
@sungwoncho I've been able to reproduce an error now.  I've got chrome, safari and Dgraph running.

* in chrome the tutorial is working fine

* in safari it doesn't work off tour.dgraph.io (reports `Error: Is Dgraph running locally?`) , but it does locally.

**Comment by TBotV63** [comment]
I'd just like to point out that I am also experiencing this due to mixed content blocking on firefox. Some sort of hint that mixed-content policies may interfere would be helpful, as the current error message is rather nondescript when it comes to the nature of the error encountered.

**Comment by aryzing** [comment]
> When you point the browser to localhost:8080 you get the dgraph UI?

Not in my case. Ratel loads in `localhost:8081`. Navigating to `localhost:8080` returns `Dgraph browser is available for running separately using the dgraph-ratel binary`

**Comment by Oroneki** [comment]
Me too: not working in firefox, but in Chrome is ok.

**Comment by webmasterraj** [comment]
Same issue here. Works fine in Chrome v60, but not Firefox v58

**Comment by kortschak** [comment]
Any idea on whether this will be fixed?

**Comment by manishrjain** [comment]
@paulftw Can you look into this?

**Comment by paulftw** [comment]
@kortschak I know it's been a while, but did you hit the issue in Firefox or Chrome?
Other users explicitly specified the problem in FF only, but I want to make sure the root cause was same in your case.

**Comment by kortschak** [comment]
Yes, I use firefox. It works with chrome.

**Comment by paulftw** [comment]
Closing as it's stale, there's been a fix more than a year ago.

we're rebuilding and retesting everything for dgraph-1.1 and if any bugs are still present they'll be picked up during release testing.
