### ISSUE TITLE
new installation of ratel UI defaults to port 8000 for dgraph

### ISSUE THREAD

**Issue by mmasouras** [dgraph-io/tutorial#50]
I followed the instructions here to set-up dgraph, successfully:
https://tour.dgraph.io/intro/2/

However, when I visit my host on port 8000 (ratel UI), it tries to find a dgraph on port 8000 as well. According to the instructions, dgraph is listening to 8080. 

This is not a huge deal, but newcomers will find that their installation does not work out-of-the box. It is also difficult to share the new ratel url since it will default to dgraph:8000 (wrong) when you open that url in a new browser, so you have to explain that they need to change the port in the UI.

**Comment by danielmai** [comment]
I just tried the instructions myself and Ratel defaults to connecting to http://localhost:8080 in the Ratel UI. Is there something special about your setup that made it go to port 8000? Did you visit the Ratel UI before and have some previous state cached in the browser? Were you running the instructions using the latest version of Dgraph?

Thanks for helping make Dgraph easier for newcomers!

**Comment by danielmai** [comment]
@mmasouras I'm gonna close this issue. Feel free to re-open it if you see it still being an issue from a clean browser session (as a newcomer would likely start with).
