### ISSUE TITLE
Rendering issue of tutorial on Firefox

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/tutorial#69]
I am not able to see/run queries on tour when I am using firefox
![Screenshot_2019-05-27 Graphs — A Tour of Dgraph](https://user-images.githubusercontent.com/15055935/58410254-6d10b180-808f-11e9-9527-ba75d541a24c.png)

**Comment by MichelDiz** [comment]
This will be solve in this PR https://github.com/dgraph-io/tutorial/pull/67
Please review it @animesh2049 

Cheers.

**Comment by paulftw** [comment]
Will be tested and fixed (if not already fixed) as part of the dgraph-1.1 work. Closing this issue without resolution
