### ISSUE TITLE
Updating tutorial as per the changes in the upcoming version

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/tutorial#73]
There are some changes that are needed for the upcoming version of Dgraph.
- Removal of pages where `_predicate_` is used, or replace it with something similar wherever required.
- Updating pages where `expand(_all_)` is used, to reflect the new changes.
- Change in all of the schemas might be required. If any node has an edge which can be more than one then `uid` should be changed to `[uid]`.
- Passing suitable headers along with the HTTP requests.

| Endpoint      |`Content-Type` header |
|---------|------------------------|
|`/alter`| N/A |
|`/mutate`|application/rdf|
|`/query`|application/graphql+-|
- For [/moredata/1](https://tour.dgraph.io/moredata/1/), change of the option for passing the file from `-r` to `-f` during live loading of the RDF dataset.

**Comment by danielmai** [comment]
There are open PRs that will address these issues:

- `_predicate_` and `expand(_all_)` will be fixed by #70.
- HTTP API changes is already a reported issue with #66 and will be fixed by #68.
- Schema changes for `[uid]` will be fixed by #58.

I don't see a PR yet that updates the live loader flags.

**Comment by MichelDiz** [comment]
All points of this issue have been merged into master.

Just "Passing suitable headers along with the HTTP requests." has changed because we are no longer using HTTP API. Just Dgraph-js-http.

Feel free to reopen if there's anything missing.
