### ISSUE TITLE
Examples don't load

### ISSUE THREAD

**Issue by d4l3k** [dgraph-io/tutorial#77]
None of the examples load.

Example URL: https://tour.dgraph.io/basic/9/
Firefox: 67.0.4
Chrome: Version 67.0.3396.99
Firefox error: `SyntaxError: fields are not currently supported index.js:17:2`

Problematic file seems to be https://tour.dgraph.io//js/runnable-url/index.js

**Comment by danielmai** [comment]
The tour works on the latest version of Chrome. I just tried the tour on Google Chrome `Version 75.0.3770.142 (Official Build) (64-bit)`.

I can confirm that this error happens on Firefox 68.0.

**Comment by paulftw** [comment]
Firefox gives me a syntax error somewhere inside runnable.js, introduced in https://github.com/dgraph-io/tutorial/commit/096cad71c8cbe7bbe606484ebc127353b7326177

Will remove that from the 1.0.16 branch

**Comment by MichelDiz** [comment]
I'm using 68.0.1 (64-bits) and I can't see this error. Also tested in 67 in Windows 7.

I'll close it feel free to reopen if it still persist.
