### ISSUE TITLE
Exercise: Integrating existing data

### ISSUE THREAD

**Issue by loganpowell** [dgraph-io/tutorial#8]
I had some trouble working out how to do [this exercise](https://tour.dgraph.io/schema/6/). I realize that the ids will be different from instance to instance, but perhaps pages which have this aspect could also elaborate on the steps to query, identify and merge datasets together? Maybe have a link at the bottom of each page connected to a github issue request like [Apollo does](http://dev.apollodata.com/react/) so that questions/problems can be more easily tracked. This might also help reduce redundant issues on Github and or Slack...

**Comment by manishrjain** [comment]
docs.dgraph.io has "edit this page". We should do the same for tutorial as well.

**Comment by MichelDiz** [comment]
I guess the mutation intro would help https://tour.dgraph.io/intro/5/

Also Bulk loader will start to export the previous UIDs and preserve it during re-import. Also We gonna have native backups (not related to this case, just mentioning) that also preserves UIDs.

Cheers.
