### ISSUE TITLE
allow tour to connect to local dgraph on non default port

### ISSUE THREAD

**Issue by aoighost** [dgraph-io/tutorial#80]
The dgraph tour requires dgraph be running on the default port. In my case I have to change the port and it breaks the tour. Please allow using a non default dgraph port.

**Comment by MichelDiz** [comment]
Not sure, that's a complicated suggestion. To use another port in Dgraph you need to explain the concept of "port offset" in Dgraph. You can't change one single port, all ports are "tangled" in an offset. And the main purpose of the Tour is just to be simple and get the learner just up and running with Dgraph.

The only binary who we could do this change is Ratel UI. Who isn't "tangled" to nothing.

**Comment by MichelDiz** [comment]
But @aoighost  what you mean by "allow"? Allow to the Tour itself access the alternate port you've chosen?

**Comment by MichelDiz** [comment]
Previously there was the option to change the default address, but it was removed due to errors in other browsers. And now it has been reintroduced.

Fixed by https://github.com/dgraph-io/tutorial/commit/fb1d74d0dc133d6516bc5e199f87c6fb3e11e260
