### ISSUE TITLE
documentation update: need schema.txt

### ISSUE THREAD

**Issue by sandys** [dgraph-io/tutorial#83]
```name: string @index(term) @lang .
age: int @index(int) .
friend: uid @count .
```

this needs to be in a schema.txt and passed in the commandline to ```dgraph live`` otherwise the read fails.
New commandline through docker is

`docker run -it  -v $(pwd):/dgraph --network=dgraph dgraph/dgraph dgraph live -v 2 -r 1million.rdf.gz -s schema.txt --zero dgraph_zero_1:5080 -d dgraph_alpha_1:9080 -c 1`

**Comment by MichelDiz** [comment]
Sorry, but where is this file?

**Comment by sandys** [comment]
you need to create it with the following content.
`age: int @index(int) .
friend: uid @count .`

**Comment by MichelDiz** [comment]
Okay, but where? here? https://tour.dgraph.io/master/moredata/1/

Most topics of this Tour you do not need to enter Schema in the command line. For within the topic itself there will be the option to change (/Alter) the Schema in the text box.

If it's not the case, I need to understand where it goes and why.

**Comment by sandys** [comment]
Yup. You have the correct url.

We are looking at production use - so we are trying out bulk loading

**Comment by MichelDiz** [comment]
The purpose of the tour is to have a basic introduction tutorial for new users to explore Dgraph. More advanced situations users should look for documentation.

The link https://docs.dgraph.io/deploy/#live-loader should cover what you looking for.

**Comment by campoy** [comment]
Hi there, @sandys 

Happy to see that you're working on a production use case! I'm the VP of Product here at Dgraph and would be very happy to help with any follow-up questions you might have.

We're also available on our [slack](https://slack.dgraph.io) and [discuss](https://discuss.dgraph.io).

**Comment by campoy** [comment]
Regarding this issue, are you saying that following the instructions of the tour in that specific page (https://tour.dgraph.io/master/moredata/1/) fails because there's some missing instructions?

**Comment by MichelDiz** [comment]
Closing this due inactivity.
