### ISSUE TITLE
Unable to load data in Dgraph while following tour.dgraph.io

### ISSUE THREAD

**Issue by ashish-goswami** [dgraph-io/tutorial#86]
While going through _https://tour.dgraph.io/_, I was trying to to load data by clicking run on page https://tour.dgraph.io/master/intro/4/#. I found it is not working for chrome/firefox. Found following errors:

**Chrome:** TypeError: Bootstrap tooltips require Popper.js (https://popper.js.org)
**Firefox:** TypeError: NetworkError when attempting to fetch resource.

I also observerd, **_POST_** call to Dgraph server was hitting different endpoints:
**Chrome:** http://localhost:8080/mutate?commitNow=true
**Firefox:** http://localhost:8080/commit?startTs=0&abort=true

**Comment by campoy** [comment]
Hey @paulftw could you have a look at this?

**Comment by prashant-shahi** [comment]
PR #87 should resolve this issue.

Also looked into the endpoints being hit across 3 different browsers. They don't seem to differ.

**Chrome**: `http://localhost:8080/mutate?commitNow=true`
**Firefox**: `http://localhost:8080/mutate?commitNow=true`
**Opera**: `http://localhost:8080/mutate?commitNow=true`

**Comment by paulftw** [comment]
Fixed in the latest version of tour.
`master` version of the tour should be used when dgraph 1.1 is running locally.
`dgraph 1.0.16` version of the tour is for users with pre-1.1 dgraphs.
An alert about the version mismatch is on the roadmap

**Comment by simonpie** [comment]
I have the same error in Safari for mac in step #3. 

I get 
`TypeError: Not allowed to request resource`
for this link: 
[https://tour.dgraph.io/intro/3/#](https://tour.dgraph.io/intro/3/#)
It works in Chrome.
